name: Wine quality Prediction
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: predict_model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          make requirements
          dvc repro
