name: Wine Quality Prediction

on: [push]

jobs:
  Predict_Wine_Quality:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: do_prediction
        run: |
          pip install -r requirements.txt
          make run_check